#!/usr/bin/perl -w
use strict;
use warnings;

my $uu=scalar(@ARGV);
if ($uu eq 0)
{
    print "Ever wondered why latex does not print directly\n";
    print "the error found in the .tex file ...\n";
    print "Use\n";
    print "LATEX_ReadLogFile [File1] [File2] .... [FileN]\n";
    print "for that\n";
    die;
}

my $nbFile=$uu;

for (my $iFile=1; $iFile<=$nbFile; $iFile++)
{
    my $eFile=$ARGV[$iFile-1];
    open(INFILE, $eFile) or die "impossible to open ".$eFile;
    my @U=<INFILE>;
    close(INFILE);
    #
    my @MultiplyDefined=();
    my @Undefined=();
    my $nbLine=scalar(@U);
    for (my $iLine=1; $iLine<=$nbLine; $iLine++)
    {
	my $eLine=$U[$iLine-1];
	my @S=split("multiply define", $eLine);
	my $nbS=scalar(@S);
	if ($nbS > 1)
	{
	    my @S2=split("'", $eLine);
	    my $str2=$S2[0];
	    my @S3=split("`", $str2);
	    my $str3=$S3[1];
	    $MultiplyDefined[scalar(@MultiplyDefined)]=$str3;
	}
	my @Sb=split("ndefined on input line", $eLine);
	my $nbSb=scalar(@Sb);
	if ($nbS > 1)
	{
	    my @S2=split("'", $eLine);
	    my $str2=$S2[0];
	    my @S3=split("`", $str2);
	    my $str3=$S3[1];
	    $Undefined[scalar(@Undefined)]=$str3;
	}
    }
    print "For file=".$eFile."\n";
    my $nbMult=scalar(@MultiplyDefined);
    if ($nbMult > 0)
    {
	print "We have ".$nbMult." multiple definition\n";
	for (my $iMult=1; $iMult<=$nbMult; $iMult++)
	{
	    my $str=$MultiplyDefined[$iMult-1];
	    print $iMult."/".$nbMult." label=".$str."\n";
	}
    }
    my $nbUndef=scalar(@Undefined);
    if ($nbUndef > 0)
    {
	print "We have ".$nbUndef." undefined labels\n";
	for (my $iUndef=1; $iUndef<=$nbUndef; $iUndef++)
	{
	    my $str=$Undefined[$iUndef-1];
	    print $iUndef."/".$nbUndef." label=".$str."\n";
	}
    }
}
