#!/usr/bin/perl -w
use strict;
use warnings;


my $uu=scalar(@ARGV);
if ($uu ne 1)
{
    print "LATEX_CheckFigureReference [TexFile]\n";
    print "with [TexFile] being a tex file\n";
    print "\n";
    print "it checks all figures and tables citations and:\n";
    print "--Check for bibliographical reference of same name\n";
    print "--Check for unused figure, table references\n";
    print "--Return statistical information for correct references\n";
    print "\n";
    print "It handles file with input and %\n";
    print "Limitations: you have to use \\cite{...} or \\citep{....}\n";
    print "and no mixture of the two is allowed\n";
    die;
}

sub PercentSplitting($)
{
    my ($strToSplit) = @_;
    my @U=split("%", $strToSplit);
    my $retPercentSplit=$U[0];
    for (my $idxSplit=1; $idxSplit<=scalar(@U)-1; $idxSplit++)
    {
	my @Lsplit=split("", $U[$idxSplit-1]);
	my $len=scalar(@Lsplit);
	if ($len > 0 && $Lsplit[$len-1] ne "\\")
	{
	    $retPercentSplit=$retPercentSplit."%".$U[$idxSplit];
	}
	else
	{
	    return $retPercentSplit;
	}
    }
#    print "eLine=".$strToSplit."\n";
#    print "retLine=".$retPercentSplit."\n";
    return $retPercentSplit;
}



my $eFile=$ARGV[0];
open(IN, $eFile) or die "impossible to open ".$eFile;
my @ListLines=<IN>;
close(IN);

for (my $iLine=0; $iLine<scalar(@ListLines); $iLine++)
{
    my $eLine=$ListLines[$iLine];
    my $eLineB=PercentSplitting($eLine);
    $ListLines[$iLine]=$eLineB;
#    print "eLineB=".$eLineB;
}



my $nbLabel1=0;
my @ListLabelInFigure=();
my @ListLabelInFigureLineNr=();
my $nbLabel2=0;
my @ListLabelInTable=();
my @ListLabelInTableLineNr=();
my $nbLabel3=0;
my @ListLabelInFigureTable=();
my @ListLabelInFigureTableLineNr=();
my $nbLabel4=0;
my @ListLabelInRef=();
my @ListLabelInRefLineNr=();

my $nbLine=scalar(@ListLines);
my $IsInFigure=0;
my $IsInTable=0;
for (my $iLine=1; $iLine<=$nbLine; $iLine++)
{
    my $eLine=$ListLines[$iLine-1];
#    @TOTu=split("", $eLine);
    my @U=split("input", $eLine);
    if (scalar(@U) > 0)
    {
	if ($U[0] eq "\\")
	{
	    print "We do not allow inputs in the .tex file when checking order of citation\n";
	    die;
	}
    }
    #
    #
    my @U2=split("begin{figure", $eLine);
    if (scalar(@U2) > 2)
    {
	print "error, two times \"begin{figure\" in one line\n";
	die;
    }
    if (scalar(@U2) > 1)
    {
	$IsInFigure=1;
    }
    my @U3=split("end{figure", $eLine);
    if (scalar(@U3) > 2)
    {
	print "error, two times \"end{figure\" in one line\n";
	die;
    }
    if (scalar(@U3) > 1)
    {
	$IsInFigure=0;
    }
    #
    #
    my @U4=split("begin{table", $eLine);
    if (scalar(@U4) > 2)
    {
	print "error, two times \"begin{table\" in one line\n";
	die;
    }
    if (scalar(@U4) > 1)
    {
	$IsInTable=1;
    }
    my @U5=split("end{table", $eLine);
    if (scalar(@U5) > 2)
    {
	print "error, two times \"end{table\" in one line\n";
	die;
    }
    if (scalar(@U5) > 1)
    {
	$IsInTable=0;
    }
    #
    #
    if ($IsInFigure == 1)
    {
	my @U6=split("label{", $eLine);
	if (scalar(@U6) > 2)
	{
	    print "error, two times \"label{\" in one line\n";
	    die;
	}
	if (scalar(@U6) > 1)
	{
	    my $str=$U6[1];
	    my @U7=split("}", $str);
	    my $eLabel=$U7[0];
	    $nbLabel1++;
	    $ListLabelInFigure[$nbLabel1-1]=$eLabel;
	    $ListLabelInFigureLineNr[$nbLabel1-1]=$iLine;
	    $nbLabel3++;
	    $ListLabelInFigureTable[$nbLabel3-1]=$eLabel;
	    $ListLabelInFigureTableLineNr[$nbLabel3-1]=$iLine;
	}
    }
    #
    #
    if ($IsInTable == 1)
    {
	my @U8=split("label{", $eLine);
	if (scalar(@U8) > 2)
	{
	    print "error, two times \"label{\" in one line\n";
	    die;
	}
	if (scalar(@U8) > 1)
	{
	    my $str=$U8[1];
	    my @U9=split("}", $str);
	    my $eLabel=$U9[0];
	    $nbLabel2++;
	    $ListLabelInTable[$nbLabel2-1]=$eLabel;
	    $ListLabelInTableLineNr[$nbLabel2-1]=$iLine;
	    $nbLabel3++;
	    $ListLabelInFigureTable[$nbLabel3-1]=$eLabel;
	    $ListLabelInFigureTableLineNr[$nbLabel3-1]=$iLine;
	}
    }
    #
    #
    my @U10=split("ref{", $eLine);
    my $nbEnt=scalar(@U10);
    for (my $i=2; $i<=$nbEnt; $i++)
    {
	my $eStr=$U10[$i-1];
	my @W=split("}", $eStr);
	my $fLabel=$W[0];
	my $IsMatch=0;
	for (my $iLabel=1; $iLabel<=$nbLabel4; $iLabel++)
	{
	    if ($ListLabelInRef[$iLabel-1] eq $fLabel)
	    {
		$IsMatch=1;
	    }
	}
	if ($IsMatch == 0)
	{
	    $nbLabel4++;
	    $ListLabelInRef[$nbLabel4-1]=$fLabel;
	    $ListLabelInRefLineNr[$nbLabel4-1]=$iLine;
	}
    }
}
my $DoCheckOrderFigureTable=0;
my $DoCheckOrderFigure=1;
my $DoCheckOrderTable=1;


if ($DoCheckOrderFigureTable == 1)
{
    my $IsCorrect=1;
    my @ListPositionFigureTable=();
    for (my $i=1; $i<=$nbLabel3; $i++)
    {
	my $ThePosition=-1;
	my $eLabel=$ListLabelInFigureTable[$i-1];
	my $iLineDef=$ListLabelInFigureTableLineNr[$i-1];
	for (my $j=1; $j<=$nbLabel4; $j++)
	{
	    if ($ThePosition == -1)
	    {
		if ($ListLabelInRef[$j-1] eq $eLabel)
		{
		    $ThePosition=$j;
		}
	    }
	}
	if ($ThePosition == -1)
	{
	    print "The label ".$eLabel." defined at line ".$iLineDef." is never cited\n";
	    $IsCorrect=0;
	}
	$ListPositionFigureTable[$i-1]=$ThePosition;
    }
    for (my $i2=2; $i2<=$nbLabel3; $i2++)
    {
	my $i1=$i2-1;
	my $iPos1=$ListPositionFigureTable[$i1-1];
	my $iPos2=$ListPositionFigureTable[$i2-1];
	if ($iPos1 > 0 && $iPos2 > 0)
	{
	    if ($iPos1 > $iPos2)
	    {
		my $eLabel1=$ListLabelInFigureTable[$i1-1];
		my $eLabel2=$ListLabelInFigureTable[$i2-1];
		my $iLine1=$ListLabelInFigureTableLineNr[$i1-1];
		my $iLine2=$ListLabelInFigureTableLineNr[$i2-1];
		my $iLineRef1=$ListLabelInRefLineNr[$iPos1-1];
		my $iLineRef2=$ListLabelInRefLineNr[$iPos2-1];
		print "Label ".$eLabel1." is defined before label ".$eLabel2."\n";
		print "   at lines ".$iLine1." and ".$iLine2."\n";
		print "   Yet it is cited after\n";
		print "   at lines ".$iLineRef1." and ".$iLineRef2."\n";
		$IsCorrect=0;
	    }
	}
    }
    if ($IsCorrect == 1)
    {
	print "Reference order and citation appear to be correct for figures and table\n";
    }
    else
    {
	print "Some errors need to be corrected\n";
	print "Order of citation of reference is as follows\n";
	for (my $iLabel=1; $iLabel<=scalar(@ListLabelInRef); $iLabel++)
	{
	    print "iLabel=".$iLabel." eLabel=".$ListLabelInRef[$iLabel-1]."\n";
	}
    }
}


if ($DoCheckOrderFigure == 1)
{
    my $IsCorrect=1;
    my @ListPositionFigure=();
    for (my $i=1; $i<=$nbLabel1; $i++)
    {
	my $ThePosition=-1;
	my $eLabel=$ListLabelInFigure[$i-1];
	my $iLineDef=$ListLabelInFigureLineNr[$i-1];
	for (my $j=1; $j<=$nbLabel4; $j++)
	{
	    if ($ThePosition == -1)
	    {
		if ($ListLabelInRef[$j-1] eq $eLabel)
		{
		    $ThePosition=$j;
		}
	    }
	}
	if ($ThePosition == -1)
	{
	    print "The label ".$eLabel." defined at line ".$iLineDef." is never cited\n";
	$IsCorrect=0;
	}
	$ListPositionFigure[$i-1]=$ThePosition;
    }
    for (my $i2=2; $i2<=$nbLabel1; $i2++)
    {
	my $i1=$i2-1;
	my $iPos1=$ListPositionFigure[$i1-1];
	my $iPos2=$ListPositionFigure[$i2-1];
	if ($iPos1 > 0 && $iPos2 > 0)
	{
	    if ($iPos1 > $iPos2)
	    {
		my $eLabel1=$ListLabelInFigure[$i1-1];
		my $eLabel2=$ListLabelInFigure[$i2-1];
		my $iLine1=$ListLabelInFigureLineNr[$i1-1];
		my $iLine2=$ListLabelInFigureLineNr[$i2-1];
		my $iLineRef1=$ListLabelInRefLineNr[$iPos1-1];
		my $iLineRef2=$ListLabelInRefLineNr[$iPos2-1];
		print "Label ".$eLabel1." is defined before label ".$eLabel2."\n";
		print "   at lines ".$iLine1." and ".$iLine2."\n";
		print "   Yet it is cited after\n";
		print "   at lines ".$iLineRef1." and ".$iLineRef2."\n";
		$IsCorrect=0;
	    }
	}
    }
    if ($IsCorrect == 1)
    {
	print "Reference order and citation appear to be correct for figures\n";
    }
    else
    {
	print "Some errors need to be corrected\n";
	print "Order of citation of reference is as follows\n";
	for (my $iLabel=1; $iLabel<=scalar(@ListLabelInRef); $iLabel++)
	{
	    print "iLabel=".$iLabel." eLabel=".$ListLabelInRef[$iLabel-1]."\n";
	}
    }
}

if ($DoCheckOrderTable == 1)
{
    my $IsCorrect=1;
    my @ListPositionTable=();
    for (my $i=1; $i<=$nbLabel2; $i++)
    {
	my $ThePosition=-1;
	my $eLabel=$ListLabelInTable[$i-1];
	my $iLineDef=$ListLabelInTableLineNr[$i-1];
	for (my $j=1; $j<=$nbLabel4; $j++)
	{
	    if ($ThePosition == -1)
	    {
		if ($ListLabelInRef[$j-1] eq $eLabel)
		{
		    $ThePosition=$j;
		}
	    }
	}
	if ($ThePosition == -1)
	{
	    print "The label ".$eLabel." defined at line ".$iLineDef." is never cited\n";
	    $IsCorrect=0;
	}
	$ListPositionTable[$i-1]=$ThePosition;
    }
    for (my $i2=2; $i2<=$nbLabel2; $i2++)
    {
	my $i1=$i2-1;
	my $iPos1=$ListPositionTable[$i1-1];
	my $iPos2=$ListPositionTable[$i2-1];
	if ($iPos1 > 0 && $iPos2 > 0)
	{
	    if ($iPos1 > $iPos2)
	    {
		my $eLabel1=$ListLabelInTable[$i1-1];
		my $eLabel2=$ListLabelInTable[$i2-1];
		my $iLine1=$ListLabelInTableLineNr[$i1-1];
		my $iLine2=$ListLabelInTableLineNr[$i2-1];
		my $iLineRef1=$ListLabelInRefLineNr[$iPos1-1];
		my $iLineRef2=$ListLabelInRefLineNr[$iPos2-1];
		print "Label ".$eLabel1." is defined before label ".$eLabel2."\n";
		print "   at lines ".$iLine1." and ".$iLine2."\n";
		print "   Yet it is cited after\n";
		print "   at lines ".$iLineRef1." and ".$iLineRef2."\n";
		$IsCorrect=0;
	    }
	}
    }
    if ($IsCorrect == 1)
    {
	print "Reference order and citation appear to be correct for tables\n";
    }
    else
    {
	print "Some errors need to be corrected\n";
	print "Order of citation of reference is as follows\n";
	for (my $iLabel=1; $iLabel<=scalar(@ListLabelInRef); $iLabel++)
	{
	    print "iLabel=".$iLabel." eLabel=".$ListLabelInRef[$iLabel-1]."\n";
	}
    }
}
