#!/usr/bin/perl -w
use strict;
use warnings;

my $uu=scalar(@ARGV);
if ($uu eq 0)
{
    print "Ever wondered why latex does not print directly\n";
    print "the error found in the .tex file ...\n";
    print "Use\n";
    print "LATEX_InsertBibtex [FileIn] [FileOut]\n";
    die;
}

my $FileI=$ARGV[0];
my $FileO=$ARGV[1];


my $TheRand=int(rand(100000));
my $order;

my $TmpDir="/tmp/BIBEXPO_".$TheRand."/";

$order="mkdir -p ".$TmpDir;
print "order=".$order."\n";
if (system($order) != 0) {
    die "The mkdir operation failed\n";
}

open(IN, $FileI) or die "impossible to open ".$FileI;
my @B=<IN>;
close(IN);
my $nbLine=scalar(@B);

sub IsStringPart($$)
{
    my ($eKeyBig, $eKeySma) = @_;
#    print "eKeySma=".$eKeySma."\n";
    my @V2=split($eKeySma, $eKeyBig);
    if (scalar(@V2) > 1)
    {
	return 1;
    }
    return 0;
}

#
# Creation of the filtered article with 
# the pictures being removed.
# This is because we need to compile with latex (not pdflatex)
# in order to get the .bbl file.
#

my $TmpFile=$TmpDir."file_filt.tex";
open(OUT, "> ".$TmpFile);
for (my $iLine=0; $iLine<$nbLine; $iLine++)
{
    my $eLine=$B[$iLine];
    my $IsFigure=0;
    #
    my @ListKey=("epsfig", "includegraphics", "epsfbox", "epsffile");
    my $nbKey=scalar(@ListKey);
    for (my $iKey=0; $iKey<$nbKey; $iKey++)
    {
	my $test=IsStringPart($eLine, $ListKey[$iKey]);
	if ($test eq 1)
	{
	    $IsFigure=1;
	}
    }
    #
    my @ListKey2=("pstex_t", "pdf_t", "pic");
    my $test1=IsStringPart($eLine, "input");
    if ($test1 eq 1)
    {
	for (my $iKey2=0; $iKey2<scalar(@ListKey2); $iKey2++)
	{
	    my $test2=IsStringPart($eLine, $ListKey2[$iKey2]);
	    if ($test2 eq 1)
	    {
		$IsFigure=1;
	    }
	}
    }
    #
    if ($IsFigure eq 1)
    {
	print OUT "\%".$eLine;
    }
    else
    {
	print OUT $eLine;
    }
}
close(OUT);

#
# Finding the lines containing the key file
#

sub ExtractTheKeyFile($)
{
    my ($eRestLine) = @_;
    my @BL=split("", $eRestLine);
    my $len=scalar(@BL);
    my $retStr="";
    for (my $i=1; $i<$len-1; $i++)
    {
	$retStr=$retStr.$BL[$i];
    }
    if ($BL[0] ne "{" || $BL[$len-1] ne "}")
    {
	print "The string should have a { in start and } at the end\n";
	print "eRestLine=".$eRestLine."\n";
	die;
    }
    return $retStr;
}


my $iLineRef=-1;

my $ClsNaked="";
my $BstNaked;
my $BibNaked;
for (my $iLine=0; $iLine<$nbLine; $iLine++)
{
    $_=$B[$iLine];
    s/\n//;
    my $eLine=$_;
    #
    my @VSL=split("", $eLine);
    my $test=IsStringPart($eLine, "bibliographystyle");
    if ($test eq 1 && $VSL[0] ne "%")
    {
	if ($iLineRef ne -1)
	{
	    print "We have two times bibliographystyle. Most likely wrong\n";
	}
	$_=$B[$iLine+1];
	s/\n//;
	my $eLineNext=$_;
	my $test2=IsStringPart($eLineNext, "bibliography");
	if ($test2 eq 0)
	{
	    print "If line iLine=".$iLine." has bibliographystyle\n";
	    print "eLine=".$eLine."\n";
	    print "and the next line should contain bibliography.\n";
	    print "Example of correct input\n";
	    print "\\bibliographystyle{springer}\n";
	    print "\\bibliography{WaveAdriaticRef}\n";
	    print "Please correct\n";
	    die;
	}
	$iLineRef=$iLine;
	#
	my @Z2=split("bibliographystyle", $eLine);
	print "eLine=".$eLine."\n";
	print "Z2[1]=".$Z2[1]."\n";
	$BstNaked = ExtractTheKeyFile($Z2[1]);
	#
	my @Z3=split("bibliography", $eLineNext);
	print "eLineNext=".$eLineNext."\n";
	print "Z3[1]=".$Z3[1]."\n";
	$BibNaked = ExtractTheKeyFile($Z3[1]);
    }
    #
    #
    #
    my @Z4=split("documentclass", $eLine);
    my $Z4siz=scalar(@Z4);
    print "Z4siz=".$Z4siz."\n";
    if (scalar(@Z4) > 1 && $VSL[0] ne "%")
    {
	print "matching\n";
	my @PSL=split("", $eLine);
	my $posOpen=-1;
	my $posClos=-1;
	for (my $pos=0; $pos<scalar(@PSL); $pos++)
	{
	    my $eChar=$PSL[$pos];
#	    print "pos=".$pos." eChar=".$eChar."\n";
	    if ($eChar eq "{")
	    {
		if ($posOpen ne -1)
		{
		    print "We have two { in the line. ILLEGAL\n";
		    die;
		}
		$posOpen=$pos;
	    }
	    if ($eChar eq "}")
	    {
		if ($posClos ne -1)
		{
		    print "We have two } in the line. ILLEGAL\n";
		    die;
		}
		$posClos=$pos;
	    }
	}
	print "posOpen=".$posOpen." posClos=".$posClos."\n";
	for (my $pos=$posOpen+1; $pos<$posClos; $pos++)
	{
	    my $eChar = $PSL[$pos];
	    $ClsNaked=$ClsNaked.$eChar;
	}
    }
    
}

#
# Copying the file to the temporary dir.
#

my $BstFull=$BstNaked.".bst";
$order="cp ".$BstFull." ".$TmpDir.$BstFull;
print "order=".$order."\n";
if (system($order) != 0) {
    die "The copy operation failed for the BstFull=".$BstFull."\n";
}

my $BibFull=$BibNaked.".bib";
$order="cp ".$BibFull." ".$TmpDir.$BibFull;
print "order=".$order."\n";
if (system($order) != 0) {
    die "The copy operation failed for the BibFull=".$BibFull."\n";
}

my $ClsFull=$ClsNaked.".cls";
$order="cp ".$ClsFull." ".$TmpDir.$ClsFull;
print "order=".$order."\n";
if (system($order) != 0) {
    die "The copy operation failed for the ClsFull=".$ClsFull."\n";
}

#
# reading the .clo files.
#

my $FileLS="/tmp/ListFile";
$order="ls *.clo > ".$FileLS;
print "order=".$order."\n";
if (system($order) != 0) {
    die "The ls operation failed\n";
}

open(INF, $FileLS) or die "impossible to open FileLS=".$FileLS."\n";
while(<INF>)
{
    chomp($_);
    my $eFileLS=$_;
    $order="cp ".$eFileLS." ".$TmpDir.$eFileLS;
    print "order=".$order."\n";
    if (system($order) != 0) {
	die "The cp operation failed\n";
    }
}

#
# Determining if we need to use latex or pdflatex
#

open(INF, $FileI) or die "impossible to open ".$File;
my @WKR=<INF>;
close(INF);

my $LatexString = "latex";
for (my $iW=0; $iW<scalar(@WKR); $iW++)
{
    my @BS=split("includegraphics", $WKR[$iW]);
    if (scalar(@WKR) > 1)
    {
        my @BS2 = split("pdf", $BS[1]);
        if (scalar(@BS2) > 1)
        {
            $LatexString = "pdflatex";
        }
    }
}


#
# Doing the creation of the latex file
#

$order="(cd ".$TmpDir." && ".$LatexString." file_filt.tex)";
print "order=".$order."\n";
if (system($order) != 0) {
    die "The latex operation failed\n";
}

$order="(cd ".$TmpDir." && bibtex file_filt.aux)";
print "order=".$order."\n";
if (system($order) != 0) {
    die "The latex operation failed\n";
}

#
# Doing the creation of the latex file
#

my $BBLfile=$TmpDir."file_filt.bbl";
open(INFILE, $BBLfile) or die "impossible to open BBLfile=".$BBLfile."\n";
my @VG=<INFILE>;
close(INFILE);





open(OUT, "> ".$FileO);
my $iLineRefP1=$iLineRef+1;
for (my $iLine=0; $iLine<$nbLine; $iLine++)
{
    if ($iLine eq $iLineRef)
    {
	print OUT @VG;
    }
    else
    {
	if ($iLine ne $iLineRefP1)
	{
	    print OUT $B[$iLine];
	}
    }
}
close(OUT);


