#!/usr/bin/perl -w
use strict;
use warnings;

my $uu=scalar(@ARGV);
if ($uu ne 2)
{
    print "LATEX_MakeElsevier [TheArch] [File]\n";
    print "with [TheArch] the arxiv arch in the form MyPaper.tar.gz\n";
    print "with [File] the .tex file\n";
    print "\n";
    print "it uses preceding functions for that goal\n";
    print "and is subject to the very same limitations:\n";
    print "\n";
    print "---The program remove remarks in percent\n";
    print "---The program creates an archive ready for submission\n";
    print "---The directory structure is unfolded\n";
    print "\n";
    die;
}

my $TheArch=$ARGV[0];
my $File=$ARGV[1];

#
# determine temporary directory
sub GetTemporaryDir($)
{
    my ($epre) = @_;
    while(1)
    {
	my $TheRand=int(rand(1000000));
	my $eWorkDir=$epre.$TheRand;
	if (-d $eWorkDir)
	{
	    print "Find an already existing directory\n";
	}
	else
	{
	    return $eWorkDir
	}
    }
    
}
my $WorkDir=GetTemporaryDir("else");
print "WorkDir=".$WorkDir."\n";
my $TmpDir="/tmp/".$WorkDir;
print "TmpDir=".$TmpDir."\n";

my $order;

$order="mkdir ".$TmpDir;
print $order."\n";
if (system($order) != 0) {
    die "Error for mkdir operation\n";
}


#
# determine archive name
my @U=split("/", $TheArch);
my $TheName=$U[scalar(@U)-1];
my @VL=split("", $TheName);
my $nb=scalar(@VL);

my $eStr="";
for (my $iChar=1; $iChar<=$nb-7; $iChar++)
{
    $eStr=$eStr.$VL[$iChar-1];
}
print "Archive name=".$eStr."\n";
my $SaveDir=$TmpDir."/".$eStr;
my $eDir =$eStr;
my $eDir1=$eStr."1";
my $eDir2=$eStr."2";
my $eDir3=$eStr."3";
my $eDir4=$eStr."4";
#$eDir5=$eStr."5";

my $SaveDir1=$TmpDir."/".$eDir1;
my $SaveDir2=$TmpDir."/".$eDir2;
my $SaveDir3=$TmpDir."/".$eDir3;
my $SaveDir4=$TmpDir."/".$eDir4;
#$SaveDir5=$TmpDir."/".$eDir5;




sub TheCleanUp()
{
    for (my $i=1; $i<=5; $i++)
    {
	my $eDir=$SaveDir.$i;
	my $order="rm -rf ".$eDir;
	print $order."\n";
	if (system($order) != 0) {
	    die "Error while doing rm operation\n";
	}
    }
    #
    my $order;
    #
    $order="rm -rf ".$SaveDir;
    print $order."\n";
    if (system($order) != 0) {
	die "Error while doing rm operation\n";
    }
    #
    $order="rm -rf ".$TmpDir;
    print $order."\n";
    if (system($order) != 0) {
	die "Error while doing rm operation\n";
    }
}

if ($VL[$nb-1] ne "z" || $VL[$nb-2] ne "g" || $VL[$nb-3] ne "\." || $VL[$nb-4] ne "r" || $VL[$nb-5] ne "a" || $VL[$nb-6] ne "t" || $VL[$nb-7] ne "\.")
{
    print "Archive name should finish in .tar.gz\n";
    TheCleanUp();
    die;
}
my @TSL=split("", $TheArch);
if ($TSL[0] ne "/")
{
    print "The archive name should be an absolute name\n";
    TheCleanUp();
    die;
}




$order="mkdir ".$SaveDir1;
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}






#
# Directory unfolding operation
# Files in pap1
#

$order="LATEX_DirectoryUnfold ".$SaveDir1." ".$File;
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

#
# Merging into a single latex file
#

$order="(cd ".$TmpDir." && cp -r ".$eDir1." ".$eDir2.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

$order="(cd ".$SaveDir2." && LATEX_FileMerging ".$File.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

#
# Removal of percent
#

$order="(cd ".$TmpDir." && cp -r ".$eDir2." ".$eDir3.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

my $LatexTemp=$TmpDir."/temp.tex";

$order="(cd ".$SaveDir3." && LATEX_RemovePercentLine < ".$File." > ".$LatexTemp.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

$order="(cd ".$SaveDir3." && mv ".$LatexTemp." ".$File.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

#
# Now renaming the figures according to Elsevier standard
#

$order="(cd ".$TmpDir." && cp -r ".$eDir3." ".$eDir4.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

$order="(cd ".$SaveDir4." && LATEX_FigureFileRenumbering 2 ".$File.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

$order="(cd ".$SaveDir4." && LATEX_BBL_merging ".$File.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

#
# Copying into the final and creating tar.gz
#

$order="(cd ".$TmpDir." && cp -r ".$eDir4." ".$eDir.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

my $eArch=$eDir.".tar.gz";

$order="(cd ".$TmpDir." && tar -c ".$eDir." | gzip > ".$eArch.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

$order="(cd ".$TmpDir." && mv ".$eArch." ".$TheArch.")";
print $order."\n";
if (system($order) != 0) {
    die "Error while doing operation\n";
}

#
# Now full cleanup
TheCleanUp();
