#!/usr/bin/perl -w

$uu=scalar(@ARGV);

if ($uu eq 0)
{
    print "Ever wondered why latex does not print directly\n";
    print "the error found in the .tex file ...\n";
    print "Use\n";
    print "LATEX_ReadLogFile [File1] [File2] .... [FileN]\n";
    print "for that\n";
    die;
}

$nbFile=$uu;

for ($iFile=1; $iFile<=$nbFile; $iFile++)
{
    $eFile=$ARGV[$iFile-1];
    open(INFILE, $eFile) or die "impossible to open ".$eFile;
    @U=<INFILE>;
    close(INFILE);
    #
    @MultiplyDefined=();
    @Undefined=();
    $nbLine=scalar(@U);
    for ($iLine=1; $iLine<=$nbLine; $iLine++)
    {
	$eLine=$U[$iLine-1];
	@S=split("multiply define", $eLine);
	$nbS=scalar(@S);
	if ($nbS > 1)
	{
	    @S2=split("'", $eLine);
	    $str2=$S2[0];
	    @S3=split("`", $str2);
	    $str3=$S3[1];
	    $MultiplyDefined[scalar(@MultiplyDefined)]=$str3;
	}
	@S=split("ndefined on input line", $eLine);
	$nbS=scalar(@S);
	if ($nbS > 1)
	{
	    @S2=split("'", $eLine);
	    $str2=$S2[0];
	    @S3=split("`", $str2);
	    $str3=$S3[1];
	    $Undefined[scalar(@Undefined)]=$str3;
	}
    }
    print "For file=".$eFile."\n";
    $nbMult=scalar(@MultiplyDefined);
    if ($nbMult > 0)
    {
	print "We have ".$nbMult." multiple definition\n";
	for ($iMult=1; $iMult<=$nbMult; $iMult++)
	{
	    $str=$MultiplyDefined[$iMult-1];
	    print $iMult."/".$nbMult." label=".$str."\n";
	}
    }
    $nbUndef=scalar(@Undefined);
    if ($nbUndef > 0)
    {
	print "We have ".$nbUndef." undefined labels\n";
	for ($iUndef=1; $iUndef<=$nbUndef; $iUndef++)
	{
	    $str=$Undefined[$iUndef-1];
	    print $iUndef."/".$nbUndef." label=".$str."\n";
	}
    }
}
