#! /usr/bin/python3
import os

if len(os.sys.argv) != 2:
    print("Program is used as")
    print("LATEX_EliminateConsecutiveEmptyLines [FileIn]")
    os.sys.exit(1)

TheFile= os.sys.argv[1]

f = open(TheFile, 'r')
ListLines = f.readlines();
f.close()

n_line = len(ListLines)


def is_empty_line(e_line):
    return len(e_line) == 0


L_Status = [True] * n_line

for iline in range(1,n_line):
    line1 = ListLines[iline-1]
    line2 = ListLines[iline]
    if is_empty(line1) and is_empty(line2):
        L_Status[iline] = False


for iline in range(n_line):
    if L_Status[iline]:
        print(ListLines[iline])
